name: Erlang build

on:
  pull_request:
    branches:
      - "*"

jobs:
  build:
    uses: valitydev/erlang-workflows/.github/workflows/erlang-parallel-build.yml@v1
    with:
      otp-version: 24
      rebar-version: 3
      use-thrift: true
      thrift-version: 0.14.2.2
